Repository JCSDA-internal/soca, pull requests merged in 2020-09, with the labels that each got.

#426 force use of GH_TOKEN in git clones
  .travis.yml
Labels: bug

#427 use crtm_COEFFICIENT_DIR to link crtm coeff
  .travis.yml
  test/CMakeLists.txt
Labels: JEDI1

#428 Add "chlorophyll" to hofx_3d ctest
  test/CMakeLists.txt
  test/Data/Obs/chl.nc
  test/testinput/hofx_3d.yml
  test/testref/hofx_3d.test
Labels: enhancement

#412 Remove global arrays in SABER
  test/testref/3dhyb.test
  test/testref/3dhybfgat.test
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarfgat.test
  test/testref/3dvarfgat_pseudo.test
  test/testref/balance_mask.test
  test/testref/checkpointmodel.test
  test/testref/dirac_soca_cov.test
  test/testref/dirac_socahyb_cov.test
  test/testref/enspert.test
  test/testref/ensrecenter.test
  test/testref/ensvariance.test
  test/testref/letkf.test
Labels: waiting for other repos

#430 change oops/parallel/mpi/mpi.h
  src/mains/CheckpointModel.h
  src/mains/GridGen.h
Labels: waiting for another PR

#435 Add a simple chlorophyll 3DVAR ctest
  src/soca/Covariance/soca_covariance_mod.F90
  src/soca/GetValues/soca_getvalues_mod.F90
  src/soca/Increment/Increment.cc
  src/soca/Increment/soca_increment_mod.F90
  src/soca/Transforms/VertConv/soca_vertconv_mod.F90
  test/Data/72x35x25/ocn.bkgerror.nc
  test/Data/Obs/chl.nc
  test/testinput/3dvar_soca.yml
  test/testref/3dvar_soca.test
Labels: enhancement

#423 DA at multiple resolution
  src/soca/Increment/Increment.cc
  src/soca/Increment/soca_increment.interface.F90
  src/soca/Increment/soca_increment_mod.F90
  src/soca/State/State.cc
  src/soca/State/soca_state.interface.F90
  src/soca/State/soca_state_mod.F90
  src/soca/Transforms/Balance/Balance.cc
  src/soca/Transforms/Balance/Balance.h
  src/soca/Transforms/Balance/BalanceFortran.h
  src/soca/Transforms/Balance/soca_balance.interface.F90
  src/soca/Transforms/Balance/soca_balance_mod.F90
  src/soca/Transforms/BkgErr/BkgErr.cc
  src/soca/Transforms/BkgErr/BkgErr.h
  src/soca/Transforms/BkgErr/BkgErrFortran.h
  src/soca/Transforms/BkgErr/soca_bkgerr.interface.F90
  src/soca/Transforms/BkgErr/soca_bkgerr_mod.F90
  src/soca/Transforms/BkgErrFilt/BkgErrFilt.cc
  src/soca/Transforms/BkgErrFilt/BkgErrFilt.h
  src/soca/Transforms/BkgErrFilt/BkgErrFiltFortran.h
  src/soca/Transforms/BkgErrFilt/soca_bkgerrfilt.interface.F90
  src/soca/Transforms/BkgErrFilt/soca_bkgerrfilt_mod.F90
  src/soca/Transforms/BkgErrGodas/BkgErrGodas.cc
  src/soca/Transforms/BkgErrGodas/BkgErrGodas.h
  src/soca/Transforms/BkgErrGodas/BkgErrGodasFortran.h
  src/soca/Transforms/BkgErrGodas/soca_bkgerrgodas.interface.F90
  src/soca/Transforms/BkgErrGodas/soca_bkgerrgodas_mod.F90
  src/soca/Transforms/HorizFilt/HorizFilt.cc
  src/soca/Transforms/HorizFilt/HorizFilt.h
  src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
  src/soca/Transforms/VertConv/VertConv.cc
  src/soca/Transforms/VertConv/VertConv.h
  src/soca/Transforms/VertConv/VertConvFortran.h
  src/soca/Transforms/VertConv/soca_vertconv.interface.F90
  src/soca/Transforms/VertConv/soca_vertconv_mod.F90
  src/soca/Utils/soca_convert_state_mod.F90
  test/CMakeLists.txt
  test/Data/subsample_mom6files.sh
  test/testinput/3dvarlowres_soca.yml
  test/testinput/convertstate.yml
  test/testinput/static_socaerrorlowres_init.yml
  test/testref/3dvarlowres_soca.test
  test/valgrind.sup
Labels: enhancement

#440 Feature/3dbump
  src/mains/3DVar.cc
  test/CMakeLists.txt
  test/testinput/3dvarbump.yml
  test/testinput/parameters_bump_cor_nicas.yml
  test/testref/3dvarbump.test
  test/testref/parameters_bump_cor_nicas.test
  test/valgrind.sup
Labels: enhancement

#445 update answers for oops pr
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarbump.test
  test/testref/3dvarlowres_soca.test
Labels: coordinate merge

#441 Added Serializable
  src/soca/Increment/Increment.h
  src/soca/ModelBias/ModelBiasIncrement.h
  src/soca/State/State.h
Labels: coordinate merge
