Repository JCSDA-internal/soca, pull requests merged in 2020-10, with the labels that each got.

#442 Parallel weak constraint and 4D-En-Var
  src/soca/Covariance/soca_covariance_mod.F90
  src/soca/Geometry/soca_geom_mod.F90
  src/soca/Increment/Increment.cc
  src/soca/Increment/Increment.h
  src/soca/Increment/IncrementFortran.h
  src/soca/Increment/soca_increment.interface.F90
  src/soca/Increment/soca_increment_mod.F90
  src/soca/State/State.cc
  src/soca/State/State.h
  src/soca/State/StateFortran.h
  src/soca/State/soca_state.interface.F90
  src/soca/State/soca_state_mod.F90
  src/soca/Traits.h
  test/testinput/3dhyb.yml
  test/testinput/3dhybfgat.yml
  test/testinput/dirac_horizfilt.yml
  test/testinput/dirac_soca_cov.yml
  test/testinput/dirac_socahyb_cov.yml
  test/testref/balance_mask.test
  test/testref/dirac_horizfilt.test
  test/testref/dirac_soca_cov.test
  test/testref/dirac_socahyb_cov.test
Labels: JEDI4

#455 fix serialize/deserialize
  src/soca/Fields/soca_fields_mod.F90
  src/soca/Increment/Increment.cc
  src/soca/Increment/soca_increment.interface.F90
  src/soca/Increment/soca_increment_mod.F90
  src/soca/State/State.cc
  src/soca/State/soca_state.interface.F90
  src/soca/State/soca_state_mod.F90
Labels: JEDI4, bug

#456 Fix after j cleanup 3
  src/soca/GetValues/GetValues.cc
Labels: bug

#444 Feature/consolidate ens app
  src/mains/EnsHofX.cc
  test/CMakeLists.txt
  test/testinput/enshofx.yml
  test/testinput/enshofx_1.yml
  test/testinput/enshofx_2.yml
  test/testinput/enshofx_3.yml
Labels: waiting for another PR

#457 fix interface and geometry iterator test
  src/soca/Increment/Increment.cc
  src/soca/Increment/IncrementFortran.h
  src/soca/Increment/soca_increment.interface.F90
  test/testinput/geometry_iterator.yml
  test/testinput/increment.yml
Labels: bug

#458 bugfix for upcoming interface/state tests
  src/soca/Fields/soca_fields_mod.F90
  src/soca/Increment/Increment.cc
  src/soca/Increment/Increment.h
  src/soca/Increment/IncrementFortran.h
  src/soca/Increment/soca_increment.interface.F90
  src/soca/State/State.cc
  src/soca/State/soca_state_mod.F90
  test/CMakeLists.txt
  test/testinput/3dhyb.yml
  test/testinput/3dhybfgat.yml
  test/testinput/3dvar_godas.yml
  test/testinput/3dvar_soca.yml
  test/testinput/3dvarbump.yml
  test/testinput/3dvarfgat.yml
  test/testinput/3dvarfgat_pseudo.yml
  test/testinput/3dvarlowres_soca.yml
  test/testinput/addincrement.yml
  test/testinput/enspert.yml
  test/testinput/ensvariance.yml
  test/testinput/forecast_identity_cice.yml
  test/testinput/increment.yml
  test/testinput/model.yml
  test/testinput/state.yml
  test/testinput/varchange_balance.yml
  test/testinput/varchange_balance_TSSSH.yml
  test/testinput/varchange_bkgerrgodas.yml
  test/testinput/varchange_vertconv.yml
  test/testref/3dhyb.test
  test/testref/3dhybfgat.test
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarbump.test
  test/testref/3dvarfgat.test
  test/testref/3dvarfgat_pseudo.test
  test/testref/3dvarlowres_soca.test
  test/testref/enspert.test
  test/testref/ensvariance.test
  test/testref/forecast_identity_cice.test
Labels: bug, syncing with jedi repo

#460 fix geom pointer
  src/soca/Increment/Increment.cc
  src/soca/Increment/Increment.h
  src/soca/State/State.cc
  src/soca/State/State.h
Labels: waiting for other repos

#465 Bye bye geostrophy
  src/soca/State/soca_state_mod.F90
  src/soca/Utils/CMakeLists.txt
  src/soca/Utils/soca_geostrophy_mod.F90
  test/testref/3dvar_godas.test
  test/testref/3dvarfgat_pseudo.test
Labels: restructure

#466 change in yaml and test output
  test/testinput/letkf.yml
  test/testref/letkf.test
Labels: waiting for other repos

#462 update letkf tests for oops/ioda fix to letkf
  test/testinput/letkf.yml
  test/testref/letkf.test
Labels: bug, waiting for another PR

#469 display bump output on main PE
  src/soca/Covariance/soca_covariance_mod.F90
  test/testinput/3dhyb.yml
  test/testinput/3dhybfgat.yml
  test/testinput/3dvar_godas.yml
  test/testinput/3dvar_soca.yml
  test/testinput/3dvarbump.yml
  test/testinput/3dvarfgat.yml
  test/testinput/3dvarfgat_pseudo.yml
  test/testinput/3dvarlowres_soca.yml
  test/testinput/dirac_horizfilt.yml
  test/testinput/dirac_soca_cov.yml
  test/testinput/dirac_socahyb_cov.yml
  test/testinput/enspert.yml
  test/testinput/parameters_bump_cor_nicas.yml
  test/testinput/parameters_bump_cov_lct.yml
  test/testinput/static_socaerror_init.yml
  test/testinput/static_socaerrorlowres_init.yml
Labels: enhancement

#471 Removed deprecated ATLASIFIED flag
  CMakeLists.txt
  src/soca/Increment/Increment.cc
  src/soca/Increment/Increment.h
Labels: coordinate merge

#476 log() and exp() transformations
  src/soca/State/State.cc
  src/soca/State/State.h
  src/soca/State/StateFortran.h
  src/soca/State/soca_state.interface.F90
  src/soca/State/soca_state_mod.F90
  src/soca/Transforms/Ana2Model/Ana2Model.cc
  src/soca/Transforms/Ana2Model/Ana2Model.h
  test/testinput/varchange_ana2model.yml
Labels: enhancement
