Repository JCSDA-internal/soca, pull requests merged in 2020-11, with the labels that each got.

#482 Feature/nl varchange
  src/soca/State/soca_state_mod.F90
  test/CMakeLists.txt
  test/testinput/3dvar_godas.yml
  test/testinput/convertstate.yml
  test/testinput/convertstate_changevar.yml
  test/testref/convertstate_changevar.test
Labels: bug, enhancement

#485 Writing the increment is now optional
  src/soca/Fields/soca_fields_mod.F90
  src/soca/Fields/soca_fieldsutils_mod.F90
  src/soca/State/soca_state_mod.F90
  test/testinput/3dvar_godas.yml
  test/testinput/addincrement.yml
Labels: enhancement

#487 Use BlaskList instead of Domain Check w/ ufo `any_bit_set_of`refactoring
  test/testinput/3dvar_soca.yml
Labels: syncing with jedi repo
