Repository JCSDA-internal/soca, pull requests merged in 2021-06, with the labels that each got.

#567 Add hybrid gain application
  src/mains/CMakeLists.txt
  src/mains/HybridGain.cc
  test/CMakeLists.txt
  test/testinput/hybridgain.yml
  test/testref/hybridgain.test
Labels: ready for merge

#585 add "irr_mix" to MOM.res.nc
  test/Data/72x35x25/INPUT/MOM.res.nc
Labels: enhancement

#589 invent bkg error for chl and biop
  src/soca/Transforms/BkgErr/soca_bkgerr_mod.F90
  src/soca/Transforms/BkgErrGodas/soca_bkgerrgodas_mod.F90
  test/testref/3dvar_soca.test
  test/testref/enspert.test
  test/testref/letkf_observer.test
  test/testref/letkf_solver.test
Labels: enhancement

#592 remove hardcoded masked interp for atmospheric flux fields
  src/soca/GetValues/soca_getvalues_mod.F90
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarfgat.test
  test/testref/checkpointmodel.test
  test/testref/hofx_3d.test
  test/testref/hofx_4d.test
Labels: bug

#596 interpolation on u/v grids
  src/soca/GetValues/soca_getvalues_mod.F90
  test/CMakeLists.txt
  test/Data/Obs/uocn_surface.nc
  test/Data/Obs/vocn_surface.nc
  test/testinput/getvalues.yml
  test/testinput/hofx_3d.yml
  test/testinput/hofx_4d.yml
  test/testref/hofx_3d.test
  test/testref/hofx_4d.test
Labels: waiting for another PR

#571 add Geometry::variableSizes()
  src/soca/Geometry/Geometry.cc
  src/soca/Geometry/Geometry.h
  src/soca/Geometry/GeometryFortran.h
  src/soca/Geometry/soca_geom.interface.F90
  src/soca/GetValues/soca_getvalues_mod.F90
Labels: waiting for another PR
