Repository JCSDA-internal/soca, pull requests merged in 2021-03, with the labels that each got.

#534 Removal of single precision constants in BUMP
  test/CMakeLists.txt
  test/testref/3dhyb.test
  test/testref/3dhybfgat.test
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarbump.test
  test/testref/3dvarfgat.test
  test/testref/3dvarfgat_pseudo.test
  test/testref/3dvarlowres_soca.test
  test/testref/enspert.test
  test/testref/ensrecenter.test
  test/testref/ensvariance.test
  test/testref/letkf.test
Labels: JEDI4, bug

#531 Barycentric Lagrange interpolation - optional
  test/testinput/parameters_bump_cor_nicas.yml
  test/testinput/parameters_bump_cov_lct.yml
  test/testinput/parameters_bump_cov_nicas.yml
  test/testinput/parameters_bump_loc.yml
  test/testinput/static_socaerror_init.yml
  test/testinput/static_socaerrorlowres_init.yml
  test/testref/3dvarbump.test
  test/testref/3dvarlowres_soca.test
  test/testref/balance_mask.test
  test/testref/dirac_soca_cov.test
Labels: JEDI4, adaptation complete

#536 Rename HofXNoModel into HofX3D
  src/mains/CMakeLists.txt
  src/mains/EnsHofX.cc
  src/mains/HofX.cc
  src/mains/HofX3D.cc
  test/CMakeLists.txt
  test/testinput/hofx_3d.yml
  test/testinput/hofx_3dcrtm.yml
  test/testref/hofx_3d.test
  test/testref/hofx_3dcrtm.test
Labels: waiting for other repos

#539 lazy fix to hofx
  src/mains/HofX3D.cc
Labels: waiting for other repos

#544 Enable ensemble perturbation and LETKF for chl and biop
  src/soca/Covariance/soca_covariance_mod.F90
  src/soca/Transforms/util/soca_bkgerrutil_mod.F90
  test/testinput/3dhyb.yml
  test/testinput/3dhybfgat.yml
  test/testinput/3dvar_godas.yml
  test/testinput/3dvar_soca.yml
  test/testinput/3dvarbump.yml
  test/testinput/3dvarfgat.yml
  test/testinput/3dvarlowres_soca.yml
  test/testinput/dirac_soca_cov.yml
  test/testinput/dirac_socahyb_cov.yml
  test/testinput/enspert.yml
  test/testinput/letkf.yml
  test/testinput/varchange_bkgerrgodas.yml
  test/testinput/varchange_bkgerrsoca.yml
  test/testref/3dhyb.test
  test/testref/3dhybfgat.test
  test/testref/3dvar_soca.test
  test/testref/dirac_socahyb_cov.test
  test/testref/enspert.test
  test/testref/ensrecenter.test
  test/testref/ensvariance.test
  test/testref/letkf.test
Labels: enhancement

#548 defaults for bkgerr min/max
  src/soca/Transforms/util/soca_bkgerrutil_mod.F90
  test/testinput/3dhyb.yml
  test/testinput/3dhybfgat.yml
  test/testinput/3dvar_godas.yml
  test/testinput/3dvarbump.yml
  test/testinput/3dvarfgat.yml
  test/testinput/3dvarlowres_soca.yml
  test/testinput/dirac_soca_cov.yml
  test/testinput/dirac_socahyb_cov.yml
  test/testinput/varchange_bkgerrgodas.yml
  test/testinput/varchange_bkgerrsoca.yml
Labels: bug
