Repository JCSDA-internal/soca, pull requests merged in 2021-01, with the labels that each got.

#499 update letkf ref for oops update
  test/testref/letkf.test
Labels: coordinate merge

#507 remove ioda-converters
  .travis.yml
  bundle/.gitignore
  bundle/CMakeLists.txt
Labels: bug

#510 Traceback and timings
  src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
  src/soca/Transforms/VertConv/soca_vertconv_mod.F90
Labels: JEDI4, enhancement

#506 Generic hybrid covariance
  test/testinput/3dhyb.yml
  test/testinput/3dhybfgat.yml
  test/testinput/dirac_socahyb_cov.yml
Labels: JEDI4

#509 fancier correlation length specifications
  src/soca/Covariance/soca_covariance_mod.F90
  test/testinput/static_socaerror_init.yml
  test/testinput/static_socaerrorlowres_init.yml
  test/testref/3dhyb.test
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarfgat.test
  test/testref/3dvarfgat_pseudo.test
  test/testref/3dvarlowres_soca.test
  test/testref/addincrement.test
  test/testref/dirac_soca_cov.test
  test/testref/dirac_socahyb_cov.test
  test/testref/enshofx.test
  test/testref/enspert.test
  test/testref/ensrecenter.test
  test/testref/ensvariance.test
  test/testref/letkf.test
Labels: waiting for other repos

#515 Bugfix in interpolation for mask boundaries checking
  test/testref/3dvarbump.test
Labels: JEDI4, bug

#508 Get randomized variance
  src/soca/Localization/Localization.cc
  src/soca/Localization/Localization.h
  src/soca/Localization/LocalizationFortran.h
  src/soca/Localization/soca_localization.interface.F90
Labels: JEDI4, enhancement

#519 add ocean "biomass" as a soca state
  src/soca/Covariance/soca_covariance_mod.F90
  src/soca/Fields/soca_fields_mod.F90
  src/soca/GetValues/soca_getvalues_mod.F90
  src/soca/Increment/Increment.cc
  src/soca/Increment/soca_increment_mod.F90
  src/soca/Transforms/VertConv/soca_vertconv_mod.F90
  test/CMakeLists.txt
  test/Data/72x35x25/ocn.bkgerror.nc
  test/Data/Obs/biomass_p.nc
  test/testinput/3dvar_soca.yml
  test/testinput/forecast_mom6_bgc.yml
  test/testinput/increment.yml
  test/testref/3dvar_soca.test
  test/testref/forecast_mom6_bgc.test
Labels: enhancement
