Repository JCSDA-internal/soca, pull requests merged in 2021-05, with the labels that each got.

#564 Test obs localization changes in UFO
  test/testinput/obslocalization.yml
Labels: coordinate merge

#572 remove OBS template parameter from instantiateObsLocFactory
  src/mains/LETKF.cc
  test/executables/TestObsLocalization.cc
Labels: waiting for another PR

#580 delete old log before running test
  test/test_wrapper.sh
Labels: bug

#578 Add jedi-cmake to bundle.
  .travis.yml
  bundle/CMakeLists.txt
Labels: bug, enhancement

#569 changes for ioda-v2
  bundle/.gitignore
  test/Data/Obs/adt.nc
  test/Data/Obs/biomass_p.nc
  test/Data/Obs/chl.nc
  test/Data/Obs/gmi_gpm_geoval.nc
  test/Data/Obs/gmi_gpm_obs.nc
  test/Data/Obs/icec.nc
  test/Data/Obs/icefb.nc
  test/Data/Obs/prof.nc
  test/Data/Obs/sss.nc
  test/Data/Obs/sst.nc
  test/testinput/3dvar_godas.yml
  test/testinput/3dvar_soca.yml
  test/testinput/3dvarfgat.yml
  test/testinput/getvalues.yml
  test/testinput/hofx_3d.yml
  test/testinput/hofx_4d.yml
  test/testinput/lineargetvalues.yml
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarfgat.test
Labels: waiting for other repos

#583 fix soca when ioda-converters is part of the bundle
  src/soca/CMakeLists.txt
Labels: bug
