Repository JCSDA-internal/soca, pull requests merged in 2021-02, with the labels that each got.

#520 adapt to changes in VariableChange in oops
  src/soca/Transforms/Ana2Model/Ana2Model.h
  src/soca/Transforms/instantiateBalanceOpFactory.h
  test/testref/convertstate_changevar.test
Labels: waiting for another PR

#529 add ioda-engines dependencies
  CMakeLists.txt
Labels: bug

#528 Initialize BUMP instance index
  src/soca/Transforms/VertConv/soca_vertconv_mod.F90
Labels: JEDI4, bug

#530 Update for the bugfix/instances branch of SABER
  src/soca/Transforms/VertConv/soca_vertconv_mod.F90
Labels: JEDI4, adaptation complete
