Repository JCSDA-internal/soca, pull requests merged in 2021-07, with the labels that each got.

#603 Fixes for tests
  test/CMakeLists.txt
  test/Data/create_kmask.py
Labels: JEDI2

#605 Generalize covariance code
  src/soca/Covariance/soca_covariance_mod.F90
  test/testinput/3dhyb.yml
  test/testinput/3dhybfgat.yml
  test/testinput/3dvar_godas.yml
  test/testinput/3dvar_soca.yml
  test/testinput/3dvarfgat.yml
  test/testinput/3dvarfgat_pseudo.yml
  test/testinput/3dvarlowres_soca.yml
  test/testinput/balance_mask.yml
  test/testinput/dirac_horizfilt.yml
  test/testinput/dirac_soca_cov.yml
  test/testinput/dirac_socahyb_cov.yml
  test/testinput/enspert.yml
  test/testinput/linearmodel.yml
  test/testinput/static_socaerror_init.yml
  test/testinput/static_socaerror_test.yml
  test/testinput/static_socaerrorlowres_init.yml
Labels: waiting for other repos

#611 Add wave 2dvar capability
  src/soca/Fields/soca_fields_mod.F90
  src/soca/Transforms/BkgErrGodas/soca_bkgerrgodas_mod.F90
  src/soca/Transforms/util/soca_bkgerrutil_mod.F90
  test/CMakeLists.txt
  test/Data/72x35x25/INPUT/wav.res.nc
  test/Data/72x35x25/wav.bkgerror.nc
  test/Data/Obs/swh.nc
  test/Data/fields_metadata.yml
  test/testinput/3dvar_soca.yml
  test/testinput/getvalues.yml
  test/testinput/static_socaerror_init.yml
  test/testref/3dvar_soca.test
Labels: enhancement

#618 Remove unused and empty Localization class
  src/soca/CMakeLists.txt
  src/soca/Fortran.h
  src/soca/Localization/CMakeLists.txt
  src/soca/Localization/Localization.cc
  src/soca/Localization/Localization.h
  src/soca/Localization/LocalizationFortran.h
  src/soca/Localization/instantiateLocalizationFactory.h
  src/soca/Localization/soca_localization.interface.F90
  src/soca/Traits.h
  test/CMakeLists.txt
  test/executables/TestLocalization.cc
Labels: draft
