Repository JCSDA-internal/soca, pull requests merged in 2023-06, with the labels that each got.

#894 switched to ens. templ.
  test/testinput/ensrecenter.yml
  test/testref/ensrecenter.test
Labels: waiting for another PR

#892 Implementation of EnsMeanAndVariance
  src/mains/CMakeLists.txt
  src/mains/EnsMeanAndVariance.cc
  test/CMakeLists.txt
  test/testinput/ensmeanandvariance.yml
  test/testref/ensmeanandvariance.test
Labels: waiting for another PR

#898 Use the generic oops interpolator
  src/soca/CMakeLists.txt
  src/soca/Covariance/soca_covariance_mod.F90
  src/soca/Fields/soca_fields_mod.F90
  src/soca/Geometry/Geometry.cc
  src/soca/Geometry/Geometry.h
  src/soca/Geometry/GeometryFortran.h
  src/soca/Geometry/soca_geom.interface.F90
  src/soca/Geometry/soca_geom_mod.F90
  src/soca/Increment/Increment.cc
  src/soca/Increment/IncrementFortran.h
  src/soca/Increment/soca_increment.interface.F90
  src/soca/Interpolator/CMakeLists.txt
  src/soca/Interpolator/LocalUnstructuredInterpolator.cc
  src/soca/Interpolator/LocalUnstructuredInterpolator.h
  src/soca/Interpolator/UnstructuredInterpolator.h
  src/soca/LinearVariableChange/HorizFilt/soca_horizfilt_mod.F90
  src/soca/State/State.cc
  src/soca/State/StateFortran.h
  src/soca/State/soca_state.interface.F90
  src/soca/Traits.h
  test/Data/obs/adt.nc
  test/Data/obs/chl.nc
  test/Data/obs/icec.nc
  test/Data/obs/icefb.nc
  test/Data/obs/prof.nc
  test/Data/obs/sst.nc
  test/testinput/getvalues.yml
  test/testinput/letkf.yml
  test/testinput/letkf_split_observer.yml
  test/testinput/obslocalization_vertical.yml
  test/testref/3dhyb.test
  test/testref/3dhybfgat.test
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarbump.test
  test/testref/3dvarfgat.test
  test/testref/3dvarfgat_pseudo.test
  test/testref/3dvarlowres_soca.test
  test/testref/addincrement.test
  test/testref/checkpointmodel.test
  test/testref/convertincrement.test
  test/testref/enshofx.test
  test/testref/hofx_3d.test
  test/testref/hofx_4d.test
  test/testref/hofx_4d_pseudo.test
  test/testref/letkf.test
  test/testref/letkf_split_observer.test
  test/testref/letkf_split_solver.test
  test/testref/makeobs.test
Labels: waiting for another PR

#899 Update version
  CMakeLists.txt
Labels: SOCA

#890 Merge B matrix-related applications
  src/mains/CMakeLists.txt
  src/mains/Dirac.cc
  src/mains/ErrorCovarianceToolbox.cc
  test/CMakeLists.txt
  test/testinput/dirac_horizfilt.yml
  test/testinput/dirac_soca_cor_nicas_scales.yml
  test/testinput/dirac_soca_cov.yml
  test/testinput/dirac_soca_mask.yml
  test/testinput/dirac_soca_nomask.yml
  test/testinput/dirac_socahyb_cov.yml
  test/testinput/increment.yml
  test/testinput/static_socaerror_init.yml
  test/testinput/static_socaerrorlowres_init.yml
  test/testref/static_socaerror_init.test
  test/testref/static_socaerrorlowres_init.test
Labels: waiting for another PR, SOCA

#902 update for VADER PR#586
  src/soca/CMakeLists.txt
  src/soca/ModelData/CMakeLists.txt
  src/soca/ModelData/ModelData.h
  src/soca/Traits.h
Labels: waiting for another PR
