Repository JCSDA-internal/soca, pull requests merged in 2023-02, with the labels that each got.

#835 Remove variables and resolution from templates
  ewok/defaults/an_variables.yaml
  ewok/defaults/bg_variables.yaml
  ewok/defaults/bstatic.yaml
  ewok/defaults/geometry_025deg.yaml
  ewok/defaults/geometry_1deg.yaml
  ewok/defaults/geometry_5deg.yaml
  ewok/defaults/model_variables.yaml
  ewok/templates/analysis.yaml
  ewok/templates/background.yaml
Labels: coordinate merge

#838 Adjust yaml spec (obsdatain) according to the removal of the "_0000" on the file name.
  test/testinput/letkf_split_solver.yml
Labels: coordinate merge

#841 Verbosity control in BUMP
  src/soca/Covariance/soca_covariance_mod.F90
Labels: waiting for another PR

#843 ctests were failing if run in a different order
  test/testinput/dirac_soca_mask.yml
  test/testinput/dirac_soca_nomask.yml
  test/testref/3dhyb.test
  test/testref/3dhybfgat.test
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarfgat_pseudo.test
  test/testref/addincrement.test
  test/testref/checkpointmodel.test
  test/testref/convertincrement.test
Labels: bug
