Repository JCSDA-internal/soca, pull requests merged in 2023-08, with the labels that each got.

#940 switch 4denvar tests to sequential, add a subwindow
  test/CMakeLists.txt
  test/testinput/4denvar.yml
  test/testinput/4dhybenvar.yml
  test/testref/4denvar.test
  test/testref/4dhybenvar.test
Labels: waiting for another PR, SOCA

#922 Change the mask value
  src/soca/Fields/soca_fields_metadata_mod.F90
  src/soca/Fields/soca_fields_mod.F90
  src/soca/LinearVariableChange/Balance/soca_balance_mod.F90
  test/Data/fields_metadata.yml
  test/testref/3dvarlowres_soca.test
  test/testref/convertstate.test
Labels: SOCA

#943 Use VADER for hofx3d test
  .travis.yml
  src/soca/VariableChange/Model2GeoVaLs/Model2GeoVaLs.F90
  src/soca/VariableChange/VariableChange.cc
  test/Data/fields_metadata.yml
  test/testinput/hofx_3d.yml
  test/testinput/obsop_name_map.yml
  test/testref/hofx_3d.test
Labels: waiting for another PR

#950 move gsw to before vader
  bundle/CMakeLists.txt
Labels: bug

#949 Atlas interface update: rename geometry fields
  src/soca/Covariance/soca_covariance_mod.F90
  src/soca/Geometry/Geometry.cc
  src/soca/Geometry/Geometry.h
  src/soca/Geometry/soca_geom_mod.F90
Labels: waiting for another PR
