Repository JCSDA-internal/soca, pull requests merged in 2024-02, with the labels that each got.

#1008 Implement defaultVariables in ModelData
  src/soca/ModelData/ModelData.h
Labels: coordinate merge

#1010 update references
  test/testinput/3dvar_godas.yml
  test/testinput/addincrement.yml
  test/testref/3dhyb_diffusion.test
  test/testref/3dhyb_nicas.test
  test/testref/3dhybfgat.test
  test/testref/3dvar_diffusion.test
  test/testref/3dvar_godas.test
  test/testref/3dvar_soca.test
  test/testref/3dvarbump.test
  test/testref/3dvarfgat.test
  test/testref/3dvarfgat_pseudo.test
  test/testref/3dvarlowres_soca.test
  test/testref/4denvar.test
  test/testref/4dhybenvar.test
  test/testref/addincrement.test
  test/testref/checkpointmodel.test
  test/testref/convertincrement.test
  test/testref/convertstate_soca2cice.test
  test/testref/hofx_3d.test
  test/testref/hofx_4d.test
  test/testref/hofx_4d_pseudo.test
  test/testref/letkf.test
  test/testref/letkf_split_observer.test
  test/testref/letkf_split_solver.test
Labels: coordinate merge

#1015 First step towards a ML based balance operator
  src/soca/CMakeLists.txt
  src/soca/MLBalance/CMakeLists.txt
  src/soca/MLBalance/MLBalance.cc
  src/soca/MLBalance/MLBalance.h
  src/soca/MLBalance/MLBalanceParameters.h
  test/CMakeLists.txt
  test/testinput/dirac_mlbalance.yml
Labels: SOCA

#1013 Add State variable change constructor
  src/soca/State/State.cc
  src/soca/State/State.h
  test/testinput/state.yml
Labels: coordinate merge

#997 Remove Parameters from interface with oops
  src/soca/AnalyticInit/AnalyticInit.h
  src/soca/ObsLocalization/ObsLocRossby.h
Labels: coordinate merge, SOCA
