Repository JCSDA-internal/soca, pull requests merged in 2024-05, with the labels that each got.

#1034 Cumulative bug fixes
  src/soca/ExplicitDiffusion/soca_diffusion.F90
  src/soca/Increment/IncrementFortran.h
  test/CMakeLists.txt
  test/mom6solo.py
  test/testinput/3dhybfgat_pseudo.yml
  test/testinput/4denvar.yml
  test/testinput/4dhybenvar.yml
  test/testinput/forecast_pseudo.yml
  test/testinput/hofx_4d_pseudo.yml
Labels: bug

#1041 add back 3dhybfgat relative tolerance
  test/testinput/3dhybfgat_pseudo.yml
Labels: bug

#1042 build mom6.x when building only soca
  test/CMakeLists.txt
Labels: bug, SOCA

#1037 Remove Geometry::latlon method
  src/soca/Geometry/Geometry.cc
  src/soca/Geometry/Geometry.h
Labels: coordinate merge

#1035 Refactor C++ Increment/State to use FieldSets, and delete lots of Fortran!
  src/soca/ExplicitDiffusion/ExplicitDiffusion.F90
  src/soca/ExplicitDiffusion/ExplicitDiffusion.cc
  src/soca/Fields/CMakeLists.txt
  src/soca/Fields/Fields.cc
  src/soca/Fields/Fields.h
  src/soca/Fields/soca_fields_metadata_mod.F90
  src/soca/Fields/soca_fields_mod.F90
  src/soca/Geometry/Geometry.cc
  src/soca/Geometry/Geometry.h
  src/soca/Geometry/GeometryFortran.h
  src/soca/Geometry/soca_geom.interface.F90
  src/soca/Geometry/soca_geom_mod.F90
  src/soca/GeometryIterator/CMakeLists.txt
  src/soca/GeometryIterator/GeometryIterator.cc
  src/soca/GeometryIterator/GeometryIterator.h
  src/soca/GeometryIterator/GeometryIteratorFortran.h
  src/soca/GeometryIterator/soca_geom_iter.interface.F90
  src/soca/GeometryIterator/soca_geom_iter_mod.F90
  src/soca/Increment/Increment.cc
  src/soca/Increment/Increment.h
  src/soca/Increment/IncrementFortran.h
  src/soca/Increment/soca_increment.interface.F90
  src/soca/Increment/soca_increment_mod.F90
  src/soca/LinearVariableChange/Balance/soca_balance.interface.F90
  src/soca/LinearVariableChange/BkgErr/soca_bkgerr.interface.F90
  src/soca/LinearVariableChange/BkgErrFilt/soca_bkgerrfilt.interface.F90
  src/soca/LinearVariableChange/BkgErrGodas/soca_bkgerrgodas.interface.F90
  src/soca/LinearVariableChange/LinearModel2GeoVaLs/LinearModel2GeoVaLs.F90
  src/soca/LinearVariableChange/LinearVariableChange.cc
  src/soca/ObsLocalization/ObsLocRossby.h
  src/soca/State/State.cc
  src/soca/State/State.h
  src/soca/State/StateFortran.h
  src/soca/State/soca_state.interface.F90
  src/soca/State/soca_state_mod.F90
  src/soca/VariableChange/Model2GeoVaLs/Model2GeoVaLs.F90
  src/soca/VariableChange/Soca2Cice/Soca2Cice.F90
  src/soca/VariableChange/VariableChange.cc
Labels: SOCA
